name: panvimdoc

on:
  push:
    paths:
      - README.md
    branches:
      - dev

jobs:
  doc:
    runs-on: ubuntu-latest
    name: readme to help
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: srcerite
          description: a colorscheme for neovim inspired by srcery
          version: "NVIM v0.5+"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'doc: auto generate help'
          branch: ${{ github.head_ref }}
          file_pattern: doc/srcerite.txt
          push_options: '--force'
