name: README to Help

on:
  push:
    paths:
      - README.md
    branches:
      - main

jobs:
  doc:
    name: README to Help
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: kdheepak/panvimdoc@v3.0.5
        with:
          vimdoc: srcerite
          description: a colorscheme for neovim inspired by srcery
          version: "NVIM v0.5+"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'doc: auto generate help'
          file_pattern: doc/srcerite.txt
          push_options: '--force'
